baseURL = "https://code.preetham.me"
languageCode = "en-us"
title = "Preetham"
theme = "hugo-theme-codex"
copyright = "© Preetham {year}"

[params]
  github = "https://github.com/preetham"
  resume = "https://github.com/preetham/resume/raw/master/kamidi_preetham_resume.pdf"
  email = "mailto:code@preetham.me"
  iconOrder = ["Github","Resume","Email"]

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "projects"
  url = "/projects"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "blog"
  url = "/blog"

[[menu.blog]]
  identifier = "roadtocode"
  name = "roadtocode"
  title = "Road to Code"
  url = "roadtocode"