baseURL = "https://tas.preetham.me"
languageCode = "en-us"
title = "Thoughts and Stories"
theme = "hugo-theme-codex"
copyright = "© Preetham {year}"

[params]
  github = "https://github.com/preetham"

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "thoughts"
  name = "thoughts"
  title = "thoughts"
  url = "/thoughts"

[[menu.main]]
  identifier = "stories"
  name = "stories"
  title = "stories"
  url = "/stories"

[deployment]
[[deployment.targets]]
name = "s3"
URL = "s3://thoughts-and-stories?region=us-east-1"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true