baseURL = "https://code.preetham.me"
languageCode = "en-us"
title = "Preetham"
theme = "hugo-theme-codex"
copyright = "© Preetham {year}"

[params]
  github = "https://github.com/preetham"

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "projects"
  name = "projects"
  title = "projects"
  url = "/projects"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "blog"
  url = "/blog"